import '~/styles/globals.css'

import { type Metadata } from 'next'
import Theme from './theme/ThemeProvider' 
// import { StoreProvider } from './_redux/StoreProvider' 

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    // <StoreProvider>
    <html lang="en">
      <body>
        <Theme themeMode={'light'}>{children}</Theme>
      </body>
    </html>
    // </StoreProvider>
  )
}
